### ISSUE TITLE
Import Assets - Colour Palette

### ISSUE THREAD

**Issue by doheekim93** [FightPandemics/FightPandemics-iOS-SwiftUI#12]
Some are already imported, import rest!

Zeplin Style Guide Link: [https://app.zeplin.io/project/5ecaeec0e0303147915effa8/styleguide/colors](https://app.zeplin.io/project/5ecaeec0e0303147915effa8/styleguide/colors)

**Comment by pyounes** [comment]
Assets imported by Luke
